services:
  # One-off HTML reports generator (run via: docker compose -f docker/docker-compose.reports.cpu.x86.yml run --rm freqai-reports-cpu-x86)
  freqai-reports-cpu-x86:
    build:
      context: ..
      dockerfile: docker/Dockerfile.cpu
    container_name: freqai_reports_cpu_x86
    restart: "no"
    environment:
      MPLBACKEND: Agg
    volumes:
      - ../user_data:/freqtrade/user_data
    working_dir: /freqtrade
    command:
      - bash
      - -lc
      - |
          set -euo pipefail
          FT_CONFIG="${FT_CONFIG:-user_data/config.json}"
          TIMERANGE="${TIMERANGE:-20240101-20250930}"
          PAIR="${PAIR:-}"
          RESULTS_JSON="${RESULTS_JSON:-}"
          if [ -z "$RESULTS_JSON" ]; then
            RESULTS_JSON="$(ls -1t user_data/backtest_results/*.json 2>/dev/null | head -n1 || true)"
          fi
          echo "[reports] Using config: $FT_CONFIG"
          echo "[reports] Using results: $RESULTS_JSON"
          if [ -z "$RESULTS_JSON" ] || [ ! -f "$RESULTS_JSON" ]; then
            echo "[reports] No results JSON found under user_data/backtest_results/" >&2
            exit 2
          fi
          if freqtrade plot-profit --help 2>/dev/null | grep -q -- "--results"; then
            freqtrade plot-profit --config "$FT_CONFIG" --results "$RESULTS_JSON"
          else
            freqtrade plot-profit --config "$FT_CONFIG" "$RESULTS_JSON" || \
            freqtrade plot-profit --config "$FT_CONFIG" --results-file "$RESULTS_JSON" || \
            freqtrade plot-profit --config "$FT_CONFIG" --result "$RESULTS_JSON"
          fi
          if [ -z "$PAIR" ]; then
            PAIR="$(python3 - <<'PY'
import json,sys
try:
    cfg=json.load(open('user_data/config.json'))
    wl=cfg.get('exchange',{}).get('pair_whitelist') or []
    print(wl[0] if wl else(''))
except Exception:
    print('')
PY
            )"
          fi
          if [ -n "$PAIR" ]; then
            freqtrade plot-dataframe --config "$FT_CONFIG" --strategy-path user_data/strategies --strategy MyRLStrategy -p "$PAIR" --timerange "$TIMERANGE" || true
          fi
          echo '[reports] HTML saved under user_data/plot/'

  # Persistent Web UI (open http://localhost:8080)
  freqai-webui-cpu-x86:
    build:
      context: ..
      dockerfile: docker/Dockerfile.cpu
    container_name: freqai_webui_cpu_x86
    restart: unless-stopped
    environment:
      FT_CONFIG: ${FT_CONFIG:-user_data/config.json}
      PYTHONFAULTHANDLER: "1"
      PYTHONUNBUFFERED: "1"
      PYTHONWARNINGS: default
      MPLBACKEND: Agg
    ports:
      - "8080:8080"
    volumes:
      - ../user_data:/freqtrade/user_data
    working_dir: /freqtrade
    command: ["bash", "-lc", "freqtrade webserver --config \"$FT_CONFIG\""]
