services:
  freqai:
    build:
      context: ..
      dockerfile: docker/Dockerfile.jetson
      args:
        BASE_IMAGE: jetson/jp6.2.1-ml:latest
    container_name: freqai_dqn_jetson
    runtime: nvidia
    restart: unless-stopped
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - DOWNLOAD_START=${DOWNLOAD_START:-20231001}
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ports:
      - "8080:8080"
    volumes:
      - ../user_data:/freqtrade/user_data
      - ../tools:/freqtrade/tools
    working_dir: /freqtrade
    command:
      - bash
      - -lc
      - |
        bash tools/download_data.sh && \
        freqtrade trade --config user_data/config.json --strategy MyRLStrategy --dry-run
