services:
  freqai-train-gpu-l4:
    build:
      context: ..
      dockerfile: docker/Dockerfile.gpu.x86
    container_name: freqai_dqn_train_gpu_l4
    gpus: all
    restart: unless-stopped
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
      # Hint for any compiled CUDA extensions (rare in this stack)
      TORCH_CUDA_ARCH_LIST: "8.9"
      TIMERANGE: ${TIMERANGE:-20240101-20250930}
      DOWNLOAD_START: ${DOWNLOAD_START:-20231001}
      PYTHONFAULTHANDLER: "1"
      PYTHONUNBUFFERED: "1"
      PYTHONWARNINGS: default
      MPLBACKEND: Agg
      # Ensure SB3 uses GPU unless overridden
      FREQAI_DEVICE: cuda
    volumes:
      - ../user_data:/freqtrade/user_data
      - ../tools:/freqtrade/tools
      - ../scripts:/freqtrade/scripts
    working_dir: /freqtrade
    command: ["python", "scripts/launch_with_all_cores.py", "--mode", "train"]
